on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Update packages
        run: apt-get update
      - name: Install dependent packages
        run: apt-get install graphviz graphviz-dev openmpi-bin openmpi-dev
      - name: Install numpy
        run: pip install numpy
      - name: build curp
        run: pip install .
      - name: View help message
        run: export PATH=$PATH:~/.local/bin && curp --help
        
